// <auto-generated />
using BookStore.Infra.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Infra.Persistence.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    partial class BookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Core.Domain.Entities.Assunto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Descricao")
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Codigo");

                    b.ToTable("Assunto", (string)null);
                });

            modelBuilder.Entity("BookStore.Core.Domain.Entities.Autor", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Nome")
                        .HasColumnType("VARCHAR(40)");

                    b.HasKey("Codigo");

                    b.ToTable("Autor", (string)null);
                });

            modelBuilder.Entity("BookStore.Core.Domain.Entities.Livro", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("AnoPublicacao")
                        .HasColumnType("VARCHAR(4)");

                    b.Property<int>("Edicao")
                        .HasColumnType("int");

                    b.Property<string>("Editora")
                        .HasColumnType("VARCHAR(40)");

                    b.Property<string>("Titulo")
                        .HasColumnType("VARCHAR(40)");

                    b.HasKey("Codigo");

                    b.ToTable("Livro", (string)null);
                });

            modelBuilder.Entity("BookStore.Core.Domain.Entities.LivroAssunto", b =>
                {
                    b.Property<int>("CodigoLivro")
                        .HasColumnType("int");

                    b.Property<int>("CodigoAssunto")
                        .HasColumnType("int");

                    b.HasKey("CodigoLivro", "CodigoAssunto");

                    b.HasIndex("CodigoAssunto");

                    b.ToTable("Livro_Assunto", (string)null);
                });

            modelBuilder.Entity("BookStore.Core.Domain.Entities.LivroAutor", b =>
                {
                    b.Property<int>("CodigoLivro")
                        .HasColumnType("int");

                    b.Property<int>("CodigoAutor")
                        .HasColumnType("int");

                    b.HasKey("CodigoLivro", "CodigoAutor");

                    b.HasIndex("CodigoAutor");

                    b.ToTable("Livro_Autor", (string)null);
                });

            modelBuilder.Entity("BookStore.Core.Domain.Entities.LivroAssunto", b =>
                {
                    b.HasOne("BookStore.Core.Domain.Entities.Assunto", "Assunto")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("CodigoAssunto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Core.Domain.Entities.Livro", "Livro")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("CodigoLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assunto");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("BookStore.Core.Domain.Entities.LivroAutor", b =>
                {
                    b.HasOne("BookStore.Core.Domain.Entities.Autor", "Autor")
                        .WithMany("LivroAutores")
                        .HasForeignKey("CodigoAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Core.Domain.Entities.Livro", "Livro")
                        .WithMany("LivroAutores")
                        .HasForeignKey("CodigoLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("BookStore.Core.Domain.Entities.Assunto", b =>
                {
                    b.Navigation("LivroAssuntos");
                });

            modelBuilder.Entity("BookStore.Core.Domain.Entities.Autor", b =>
                {
                    b.Navigation("LivroAutores");
                });

            modelBuilder.Entity("BookStore.Core.Domain.Entities.Livro", b =>
                {
                    b.Navigation("LivroAssuntos");

                    b.Navigation("LivroAutores");
                });
#pragma warning restore 612, 618
        }
    }
}
